# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -f /usr/lib/git-core/git-sh-prompt ]; then
  source /usr/lib/git-core/git-sh-prompt
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
  else
    color_prompt=
  fi
fi

# Profile Commands by adding the date
#PS4='+ $(date "+%s.%N")\t'

if [ "$color_prompt" = yes ]; then
  if [ $(id -u) == 0 ]; then
    PS1="\[\e[0m\]${debian_chroot:+($debian_chroot)}\[\e]0;\u@\h: \w\a\]\[\e[0;31m\]\u@\h\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[0;31m\]\\$ \[\e[m\]\[\e[0;32m\]$(__git_ps1) "
    #PS1="\[\e[0m\]${debian_chroot:+($debian_chroot)}\[\e]0;\u@\h: \w\a\]\[\e[0;31m\]\u@\h\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[0;31m\]\\$ \[\e[m\]\[\e[0;32m\] "
  else
    PS1="\[\e[0m\]${debian_chroot:+($debian_chroot)}\[\e[00;32m\]\u@\h\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[01;36m\]\w\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[00;32m\]\\$\[\e[0m\]\[\e[00;37m\]\[\e[0m\]$(__git_ps1) "
    #PS1="\[\e[0m\]${debian_chroot:+($debian_chroot)}\[\e[00;32m\]\u@\h\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[01;36m\]\w\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[00;32m\]\\$\[\e[0m\]\[\e[00;37m\]\[\e[0m\] "
  fi
  if /usr/bin/which prompt_banner_gen > /dev/null 2>&1; then
    PS1="$(prompt_banner_gen)${PS1}"
  fi
else
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
  PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# make vim the default editor
export VISUAL="vim"
export EDITOR="$VISUAL"

# set up local AI tools
export OLLAMA_API_BASE="http://localhost:11434"
#export ANTHROPIC_BASE_URL="${OLLAMA_API_BASE}"
#export ANTHROPIC_API_KEY=""
#export ANTHROPIC_AUTH_TOKEN="ollama"
export ANTHROPIC_BASE_URL="http://localhost:4000"
export ANTHROPIC_API_KEY="sk-12345"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
  # Initial load of bash_aliases
  . ~/.bash_aliases

  # Reload bash_aliases before each command
  trap '. ~/.bash_aliases' DEBUG
fi

#if [ -f /usr/local/bin/duiker ]; then
#  __duiker_import() {
#    local old_histignore=$HISTIGNORE
#    HISTIGNORE='history*'
#    history 1 | duiker import --quiet -
#    HISTIGNORE=$old_histignore
#  }

#  trap '__duiker_import' DEBUG
#fi

# add all ssh keys to ssh-agent via keychain
#ssh-agent 2>&1 > /dev/null
#for key in $(ls ~/.ssh/id_* 2>/dev/null | grep -Ev ".pub|.bak"); do
#  ssh-add ${key} &> /dev/null
#done
keychain $(ls ~/.ssh/id_* 2>/dev/null | grep -Ev ".pub|.bak") > /dev/null 2>&1
if [ -f ~/.keychain/${HOSTNAME}-sh ]; then
  source ~/.keychain/${HOSTNAME}-sh
fi
if [ -f ~/.keychain/${HOSTNAME}-sh-gpg ]; then
  source ~/.keychain/${HOSTNAME}-sh-gpg
fi

#Add asdf-vm shims
#if [ -f ~/.asdf/asdf.sh ]; then
#  source ~/.asdf/asdf.sh
#fi

# Add NPM Shims
if [ -d ~/.npm-packages ]; then
  export NPM_PACKAGES="${HOME}/.npm-packages"
  export MATHPATH="${MANPATH-$(manpath)}:${NPM_PACKAGES}/share/man"
fi

custom_paths=( "/usr/local/go/bin" "${HOME}/.pyenv/shims" "${HOME}/.bin" "${HOME}/.local/bin" "${HOME}/.cargo/bin" "${KREW_ROOT:-$HOME/.krew}/bin" "${HOME}/go/bin" "${NPM_PACKAGES}/bin" "${HOME}/.rbenv/bin" "${HOME}/.rbenv/shims" "${HOME}/.rbenv/plugins/ruby-build/bin" "/usr/lib/ccache" "${HOME}/.opencode/bin"  )

for custom_path in "${custom_paths[@]}"; do
  if [ -d "${custom_path}" ]; then
    #if echo "${PATH}" | grep -Pqv "(:${custom_path}|${custom_path}:)"; then
    if [[ $PATH != *":$custom_path:"* && $PATH != "$custom_path:"* ]]; then
      export PATH="${custom_path}:${PATH}"
    fi
  fi
done

# Add PyEnv Shims
#if [ -f ${HOME}/.pyenv/shims ]; then
#  export PATH="${HOME}/.pyenv/shims:${PATH}"
#fi

# Add PipX
#if [ -d ${HOME}/.local/bin ]; then
#  export PATH="${HOME}/.local/bin:${PATH}"
#fi

# Add Cargo
#if [ -d ${HOME}/.cargo/bin ]; then
#  export PATH="${HOME}/.cargo/bin:${PATH}"
#fi

# Add Go
#if [ -d ${GOPATH}/bin ]; then
#  export PATH="${GOPATH}/bin:${PATH}"
#fi
#if [ -d /usr/local/go/bin ]; then
#  export PATH="/usr/local/go/bin:${PATH}"
#fi

# Add ccache before all other PATHs
#if [ -d /usr/lib/ccache ]; then
#  export PATH=/usr/lib/ccache:$PATH
#fi

if [ -f ${HOME}/.cargo/env ]; then
  source "${HOME}/.cargo/env"
fi

#if [ -x ${HOME}/.cargo/bin/starship ]; then
#  eval "$(${HOME}/.cargo/bin/starship init bash)"
#fi

if [ -f /run/user/$(id -u)/docker.sock ]; then
  export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
fi

if [ -f "${HOME}/.rbenv/completions/rbenv.bash" ]; then
  source "${HOME}/.rbenv/completions/rbenv.bash"
fi

#if [ -f ${HOME}/.local/share/blesh/ble.sh ]; then
  #[[ $- == *i* ]] && source ${HOME}/.local/share/blesh/ble.sh --noattach --rcfile ${HOME}/.blerc
  #if [ -x $(which atuin) ]; then
  #  eval "$(atuin init bash)"
  #fi
#fi
#if [ -f "${HOME}/.deno/env" ]; then
#  source "${HOME}/.deno/env"
#fi
#if [ -f "${HOME}/.local/share/bash-completion/completions/deno.bash" ]; then
#  source "${HOME}/.local/share/bash-completion/completions/deno.bash"
#fi


# >>> grok installer >>>
export PATH="$HOME/.grok/bin:$PATH"
[[ -r "$HOME/.grok/completions/bash/grok.bash" ]] && source "$HOME/.grok/completions/bash/grok.bash"
# <<< grok installer <<<
